# Generated by Django 3.2.5 on 2021-09-17 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TradingCenter', '0002_alter_service_featurers_manager_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='accounts_turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date', models.DateTimeField()),
                ('ending_date', models.DateTimeField()),
                ('is_complete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TradingCenter.customer')),
            ],
        ),
        migrations.CreateModel(
            name='service_portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_short_description', models.TextField()),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('project_url_link', models.URLField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TradingCenter.services_manager')),
            ],
        ),
        migrations.CreateModel(
            name='cash_out',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TradingCenter.accounts_turn')),
            ],
        ),
        migrations.CreateModel(
            name='cash_in',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TradingCenter.accounts_turn')),
            ],
        ),
    ]
