# Generated by Django 3.2.5 on 2021-09-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TradingCenter', '0003_accounts_turn_cash_in_cash_out_service_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash_in',
            name='description',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cash_out',
            name='description',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
