# Generated by Django 3.2.5 on 2021-09-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TradingCenter', '0005_alter_accounts_turn_ending_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts_turn',
            name='activate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accounts_turn',
            name='total_gain',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='accounts_turn',
            name='starting_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
